# Parts
parts_get:
    path:     /parts/get
    defaults: { _controller: AppBundle:Parts:get }
    methods:  [GET]
parts_view:
    path:     /parts/view/{partId}
    defaults: { _controller: AppBundle:Parts:view }
    methods:  [GET]
parts_dashboard:
    path:     /
    defaults: { _controller: AppBundle:Parts:index }
    methods:  [GET]
parts_add:
    path:     /parts/add
    defaults: { _controller: AppBundle:Parts:add }
parts_find:
    path:     /parts/find
    defaults: { _controller: AppBundle:Parts:find }
    methods:  [GET]
parts_manage:
    path:     /parts/manage
    defaults: { _controller: AppBundle:Parts:manage }
    methods:  [GET]

# Locations
locations_get:
    path:     /locations/get
    defaults: { _controller: AppBundle:Locations:get }
    methods:  [GET]
locations_delete:
    path:     /locations/delete
    defaults: { _controller: AppBundle:Locations:delete }
    methods:  [POST]
locations_manage:
    path:     /locations/manage
    defaults: { _controller: AppBundle:Locations:manage }
locations_edit:
    path:     /locations/edit/{id}
    defaults: { _controller: AppBundle:Locations:edit }

# Part Types
parts_types_get:
    path:     /parttypes/get
    defaults: { _controller: AppBundle:PartTypes:get }
    methods:  [GET]
part_types_manage:
    path:     /parttypes/manage
    defaults: { _controller: AppBundle:PartTypes:manage }

# Help
article:
    path:     /help/{_article}
    defaults: { _controller: AppBundle:PartTypes:add,_article:"parts"}
    methods:  [GET]

# Users
login:
    path:     /login
    defaults: { _controller: AppBundle:Site:login }
users_login_check:
    path:     /login_check
users_add:
    path:     /users/add
    defaults: { _controller: AppBundle:User:add }
users_manage:
    path:     /users/manage
    defaults: { _controller: AppBundle:User:manage }
    methods:  [GET]
users_get:
    path:     /users/get
    defaults: { _controller: AppBundle:User:get }
    methods:  [GET]
logout:
    path: /logout
