<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PartTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartTypeRepository extends EntityRepository
{
    public function getTypeList()
    {
        return array();
    }
}
