<?php

/**
 * User Repository
 *
 * PHP version 5.6
 *
 * @category WPM
 * @package  User
 * @author   Matthew Turner <tmatt95@gmail.com>
 * @license  http://opensource.org/licenses/GPL-3.0 GPL3
 * @version  GIT: <1.0.0>
 * @link     https://github.com/tmatt95/WPM/
 */

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * User Repository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * PHP version 5.6
 *
 * @category WPM
 * @package  User
 * @author   Matthew Turner <tmatt95@gmail.com>
 * @license  http://opensource.org/licenses/GPL-3.0 GPL3
 * @version  Release: <1.0.0>
 * @link     https://github.com/tmatt95/WPM/
 */
class UserRepository extends EntityRepository
{
}
